# Generated by Django 2.2.6 on 2019-10-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0003_auto_20191027_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shepp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('male', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
            ],
        ),
    ]
