# Generated by Django 2.2.5 on 2019-09-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('via_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('AZE', 'Azerbaijan'), ('USA', 'USA'), ('IRA', 'Iran'), ('TR', 'Turkey')], max_length=70),
        ),
    ]
