# Generated by Django 2.2.5 on 2019-09-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('via_accounts', '0002_auto_20190910_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=255, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('TR', 'Turkey'), ('AZE', 'Azerbaijan'), ('USA', 'USA'), ('IRA', 'Iran')], max_length=70),
        ),
    ]
