# Generated by Django 2.2.5 on 2019-09-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_auto_20190908_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image5',
        ),
    ]
